app:
  domain: "host2play.com"
  port: "7006"
  uuid: "3f249584-3283-4d58-a84e-d281b22a6d08"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: ""
  argo-token: ""
  remarks-prefix: "host2play"
